# Generated by Django 5.1 on 2024-12-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("photo", models.URLField()),
                ("website", models.URLField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
