# Generated by Django 5.1 on 2024-12-16 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-sent_at',), 'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sent_on',
        ),
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='resposta'),
        ),
        migrations.AddField(
            model_name='contact',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='respondido em'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='recebido em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=255, verbose_name='mensagem'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='telefone'),
        ),
    ]
